baseURL = "https://avanderw.co.za/"
publishDir = "docs"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Andrew van der Westhuizen"
theme = "anatole"

[params]
profilePicture = "images/profile.png"
title = "Andrew van der Westhuizen"
author = "Andrew van der Westhuizen"
description = "aka 'avanderw'"
favicon = "favicons/"
displayMode = "dark"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/avanderw/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/avanderw/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:avanderw@gmail.com"

[[params.socialIcons]]
icon = "fa-steam"
title = "Steam"
url = "https://steamcommunity.com/id/avanderw"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"